[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.10.0"
prost = "0.13"
prost-types = "0.13"
solana-perf = "2.1.13"
solana-sdk = "2.1.13"
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
